# Generated by Django 4.1.7 on 2023-05-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_logo_image_button1_logo_image_button2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.IntegerField(default='9876543210')),
                ('email', models.CharField(default='ram@gmail.com', max_length=100)),
                ('address', models.CharField(default='Hyderabad-Telangana', max_length=100)),
            ],
        ),
    ]
